### ISSUE TITLE
Verbesserungen

### ISSUE THREAD

**Issue by IGGYvanHouten** [BigETI/TruckingVSConnect2#1]
- [x] Kommastellen streichen (Geschwindigkeit, Schaden etc.).
- [x] Button Längeneinheit neu platzieren (links neben Abmelden).
- [x] Meldung "Später nachfüllen" ändern in "Nachtanken erforderlich".
- [x] Warnmeldungen "rot" ausgeben (Tankanzeige etc.).
- [x] Zeilen übersichtlicher gestalten bsp.:
Ertrag: (in €)
Gewicht: (in kg)
...
Fahrtstrecke: (in km und m)
Fahrtzeit: (in std. und min.)

**Comment by BigETI** [comment]
Danke für die Vorschläge. Die wurden für den nächsten Patch realisiert.
