### ISSUE TITLE
Vorschläge

### ISSUE THREAD

**Issue by Crackbone11** [BigETI/TruckingVSConnect2#4]
Trucking VS Connect² Vorschläge:

1: Unten

- [x] 1.1: Geschwindigkeit in km/h gegen einen Fahrtenschreiber austauschen.
Von Anfang bis Ende einer Lieferung.

- [x] 1.2: Jede Fahrt als ein Bildschirmfoto des Fensters abspeichern.
 
![unbenannt](https://user-images.githubusercontent.com/35176938/34644250-16aa74f6-f333-11e7-9b49-82da471f53fe.png)

2: Rechts
- [x] 2.1: Prozentzahl des Schadensbild nicht von 100% sondern wie im Spiel bei 0% Schaden anfangen.
- [x] 3.2: Treibstoff
Jetzt: 1,14l/km
Neu: 114 l / 100 km
- [x] 3.3: Optional
Evlt. so wie Schadensmodel auch eine Tankanzeige bauen.
 ![unbenannt2](https://user-images.githubusercontent.com/35176938/34644261-34ca74c2-f333-11e7-8b97-04e2b49e7cb5.png)
![unbenannt2 1](https://user-images.githubusercontent.com/35176938/34644256-2c6d395e-f333-11e7-8cbe-1763556015d1.png)
![unbenannt2 2](https://user-images.githubusercontent.com/35176938/34644258-2f1ab190-f333-11e7-862f-3123913a0252.png)
![unbenannt2 3](https://user-images.githubusercontent.com/35176938/34644260-313c2260-f333-11e7-8872-b255816eef7c.png)

3: Links

- [x] 3.1: Fahrstrecke :   
Jetzt: 548 km von 548 km ( 100% )
Neu: 0 km von 548 km ( 0% )
- [x] 3.2: Fahrtzeit
Jetzt: 19h 22m von 19h 22m
Neu: z.b. Restfahrtzeit 19:22h
- [x] 3.3: Gewicht
Jetzt: 28.200 kg
Neu: 28,20 t
- [x] 3.4: Gefahrene Gesamtstrecke in einer ganzen Sitzung
- [x] 3.5: Gefahrens Gesamtgewicht in einer ganzen Sitzung
- [x] 3.6: Verdientes Geld pro Tag für die Firma wie oben

**Comment by BigETI** [comment]
Ich bräuchte mindestens 2 Bilder für die Tankanzeige, wo die Nadel senkrecht steht, und sich horizontal bewegt.

**Comment by Crackbone11** [comment]
hier deine bilder da du ja den ordner nicht downloaden wolltest 

![1 00](https://user-images.githubusercontent.com/35176938/34687471-234ae4ca-f4af-11e7-997e-715bc03d7eb1.png)
![1 50](https://user-images.githubusercontent.com/35176938/34687472-236dc79c-f4af-11e7-8f16-50c5f361ea9b.png)
![2 00](https://user-images.githubusercontent.com/35176938/34687473-238d04e0-f4af-11e7-979a-643e848473c0.png)
![2 50](https://user-images.githubusercontent.com/35176938/34687474-23ac8de2-f4af-11e7-977c-a95030d114dc.png)
![3 00](https://user-images.githubusercontent.com/35176938/34687475-23c857a2-f4af-11e7-9a52-b8e9c64b54e3.png)
![3 50](https://user-images.githubusercontent.com/35176938/34687476-23e4fdb2-f4af-11e7-9211-c030480ac8fa.png)
![4 00](https://user-images.githubusercontent.com/35176938/34687477-24154418-f4af-11e7-9fd5-16f400544c48.png)
![4 50](https://user-images.githubusercontent.com/35176938/34687478-242e460c-f4af-11e7-8ca1-4ae8c4892e34.png)
![5 00](https://user-images.githubusercontent.com/35176938/34687479-244c59c6-f4af-11e7-8ecb-1d2d8b860c93.png)
![5 50](https://user-images.githubusercontent.com/35176938/34687480-246bff06-f4af-11e7-9b16-555442c5dad9.png)
![6 00](https://user-images.githubusercontent.com/35176938/34687481-248b5b80-f4af-11e7-9a08-a1fb92d082f0.png)
![6 50](https://user-images.githubusercontent.com/35176938/34687482-24a62b5e-f4af-11e7-975d-8590f407a72e.png)
![7 00](https://user-images.githubusercontent.com/35176938/34687483-24c830be-f4af-11e7-9236-12c26c62b863.png)
![7 50](https://user-images.githubusercontent.com/35176938/34687484-24e532b8-f4af-11e7-9d49-af3e60bcc3f5.png)
![8 00](https://user-images.githubusercontent.com/35176938/34687486-2504f22e-f4af-11e7-8995-a88acf20ab52.png)
![8 50](https://user-images.githubusercontent.com/35176938/34687487-2524589e-f4af-11e7-815c-b57680b4a34f.png)
![9 00](https://user-images.githubusercontent.com/35176938/34687488-25405030-f4af-11e7-8f7c-fec1f3bc4432.png)
![9 50](https://user-images.githubusercontent.com/35176938/34687490-255da91e-f4af-11e7-9c7d-ad884ea6effc.png)
![10 00](https://user-images.githubusercontent.com/35176938/34687491-25774f86-f4af-11e7-86b7-ffa7aab1d31c.png)
![10 50](https://user-images.githubusercontent.com/35176938/34687492-2598265c-f4af-11e7-8dde-6de2f83285f8.png)
![11 00](https://user-images.githubusercontent.com/35176938/34687493-25b71cba-f4af-11e7-9ff3-97ea2535aa65.png)
![11 50](https://user-images.githubusercontent.com/35176938/34687494-25d1f594-f4af-11e7-9e28-53baf7a6a4d5.png)
![12 00](https://user-images.githubusercontent.com/35176938/34687495-25ef5440-f4af-11e7-8e19-0497ec72a4f0.png)
![12 50](https://user-images.githubusercontent.com/35176938/34687496-2609d158-f4af-11e7-9d25-87bc2f7191d3.png)
![13 00](https://user-images.githubusercontent.com/35176938/34687498-266f63c4-f4af-11e7-9dd5-d1153cc951b6.png)
![13 50](https://user-images.githubusercontent.com/35176938/34687499-268fbc78-f4af-11e7-9715-1f384d80a93e.png)
![14 00](https://user-images.githubusercontent.com/35176938/34687500-26af3d5a-f4af-11e7-9840-3956d4b395a3.png)
![14 50](https://user-images.githubusercontent.com/35176938/34687501-26ceec18-f4af-11e7-8665-b3e76fc40034.png)
![15 00](https://user-images.githubusercontent.com/35176938/34687502-26f10a28-f4af-11e7-96a4-31dad153d726.png)
![15 50](https://user-images.githubusercontent.com/35176938/34687504-27140046-f4af-11e7-9f22-23c5dfdf7f50.png)
![16 00](https://user-images.githubusercontent.com/35176938/34687505-2730be02-f4af-11e7-8030-738e80ccada5.png)
![17 50](https://user-images.githubusercontent.com/35176938/34687506-274c732c-f4af-11e7-8a13-89bdd222452b.png)
![18 00](https://user-images.githubusercontent.com/35176938/34687507-276bccfe-f4af-11e7-9c70-9684eddb0bee.png)
![18 50](https://user-images.githubusercontent.com/35176938/34687508-278bcb12-f4af-11e7-815c-7e4e200319be.png)
![19 00](https://user-images.githubusercontent.com/35176938/34687509-27ab2eee-f4af-11e7-86ec-a69f849a2a6e.png)
![19 50](https://user-images.githubusercontent.com/35176938/34687510-27cf317c-f4af-11e7-8f7b-9aae3cc25976.png)
![t20 00](https://user-images.githubusercontent.com/35176938/34687511-27ec06da-f4af-11e7-9588-7949b475824a.png)
![tank planko](https://user-images.githubusercontent.com/35176938/34687512-2810a756-f4af-11e7-8473-4a7ced0e79d5.png)
![unbenannt](https://user-images.githubusercontent.com/35176938/34687513-2834d45a-f4af-11e7-8fa1-ae32c74f65e3.png)
